forum:
    resource: "@ForumBundle/Resources/config/routing.yml"
    prefix:   /
location:
    resource: "@LocationBundle/Resources/config/routing.yml"
    prefix:   /location


login:
    resource: "@LoginBundle/Resources/config/routing.yml"
    prefix:   /
montage:
    resource: "@MontageBundle/Resources/config/routing.yml"
    prefix:   /montage

demande:
    resource: "@DemandeBundle/Resources/config/routing.yml"
    prefix:   /demande

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

event:
    resource: "@EventBundle/Resources/config/routing.yml"
    prefix:   /
e_commerce:
    resource: "@ECommerceBundle/Resources/config/routing.yml"
    prefix:   /
