montage:
    resource: "@MontageBundle/Resources/config/routing.yml"
    prefix:   /montage

test:
    resource: "@TestBundle/Resources/config/routing.yml"
    prefix:   /test

demande:
    resource: "@DemandeBundle/Resources/config/routing.yml"
    prefix:   /demande

login:
    resource: "@LoginBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"




