Register:
  path:     /register/
  defaults: { _controller: LoginBundle:Registration:register }

profile:
  path:     /profile/
  defaults: { _controller: LoginBundle:Profile:show }

trophets:
  path:     /profile/trophets
  defaults: { _controller: LoginBundle:Profile:trophets }

informations:
  path:     /profile/informations
  defaults: { _controller: LoginBundle:Profile:informations }
